// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CheckboxInput: typeof import('./components/CheckboxInput.vue')['default']
    Console: typeof import('./components/Console.vue')['default']
    CustomField: typeof import('./components/CustomField.vue')['default']
    EmailField: typeof import('./components/EmailField.vue')['default']
    FormCompositionOptionsApi: typeof import('./components/FormCompositionOptionsApi.vue')['default']
    NumberField: typeof import('./components/NumberField.vue')['default']
    PasswordField: typeof import('./components/PasswordField.vue')['default']
    RadioInput: typeof import('./components/RadioInput.vue')['default']
    SelectField: typeof import('./components/SelectField.vue')['default']
    TextAreaField: typeof import('./components/TextAreaField.vue')['default']
    TextField: typeof import('./components/TextField.vue')['default']
    ValidationEmail: typeof import('./components/ValidationEmail.vue')['default']
    ValidationMax: typeof import('./components/ValidationMax.vue')['default']
    ValidationMaxLength: typeof import('./components/ValidationMaxLength.vue')['default']
    ValidationMin: typeof import('./components/ValidationMin.vue')['default']
    ValidationMinLength: typeof import('./components/ValidationMinLength.vue')['default']
    ValidationPattern: typeof import('./components/ValidationPattern.vue')['default']
    ValidationRequired: typeof import('./components/ValidationRequired.vue')['default']
    ValidationUrl: typeof import('./components/ValidationUrl.vue')['default']
  }
}

export { }
