// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CheckboxInput: typeof import('./components/checkbox-input/CheckboxInput.vue')['default']
    CodiconGithub: typeof import('~icons/codicon/github')['default']
    Console: typeof import('./../demos/vue-3/src/components/Console.vue')['default']
    DynamicForm: typeof import('./components/dynamic-form/DynamicForm.vue')['default']
    DynamicInput: typeof import('./components/dynamic-input/DynamicInput.vue')['default']
    IonDocumentTextOutline: typeof import('~icons/ion/document-text-outline')['default']
    NumberInput: typeof import('./components/number-input/NumberInput.vue')['default']
    RadioInput: typeof import('./components/radio-input/RadioInput.vue')['default']
    SelectInput: typeof import('./components/select-input/SelectInput.vue')['default']
    TextAreaInput: typeof import('./components/text-area-input/TextAreaInput.vue')['default']
    TextInput: typeof import('./components/text-input/TextInput.vue')['default']
    Toolbar: typeof import('./../demos/vue-3/src/components/Toolbar.vue')['default']
  }
}

export { }
